# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Local hook to validate context.md presence
  - repo: local
    hooks:
      - id: validate-context
        name: validate context.md files
        entry: python tools/validate_context.py
        language: python
        # Specify the files that trigger this hook, e.g., any file change
        # You might refine this later
        types: [file]
        pass_filenames: false # Don't pass filenames to the script
