version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ourmoney
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ourmoney
    depends_on:
      - db

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.frontend
    command: npm run dev -- --host
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
